### ISSUE TITLE
API docs are broken

### ISSUE THREAD

**Issue by lukasgraf** [4teamwork/ftw.testbrowser#61]
The API docs currently seem to be broken: http://ftwtestbrowser.readthedocs.io/en/stable/api_browser.html

Probably an issue with the Sphinx `autodocs` extension.

![ftw_testbrowser_apidocs](https://user-images.githubusercontent.com/405124/27324631-1fe3c8fe-55a6-11e7-9fda-72d34dc5a838.png)

**Comment by jone** [comment]
I could fix the build for the new version `1.24.3` and `stable`. Older versions are still broken.
The problem was that read the docs installed all requirements in `setup.py`, but didn't have our version pinnings.

It is important that all dependencies are installed in order to include the source documentation, since Sphinx needs to import the python modules without `ImportError`s.

I've now added a `rtd-requirements.txt`, which can be automatically generated with the `rtd-update-requirements.py` script (on a local developer notebook after running buildout sucessfully). It contains all important dependencies with their versions.
The requirements file does not include the packages which rtd installs with a specific version, such as sphinx itself.
